import turtle

turtle.bgcolor("black")
t = turtle.Turtle()
turtle.speed(1)
t.color("white")
t.begin_fill()
t.fillcolor("red")
t.left(140)
t.forward(180)
t.circle(-90,200)
t.setheading(60)
t.circle(-90,200)
t.forward(180)
t.end_fill()
t.write("          Seviyoz İşte","true",'left',font=('open sans',15))